language: bash

services:
  - docker

sudo: required

branches:
  only:
    - master

script:
  - echo "$CONFIG" > src/config.json
  - docker build -t lhzbxx/love-letter-bot .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lhzbxx/love-letter-bot
